on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        with:
          script: |
            const script = require('./.github/update_nightly.js');
            await script({github, core});

      - run: git diff --exit-code || git -c user.email='github-actions[bot]@users.noreply.github.com' -c user.name='github-actions[bot]' commit -a -m 'Update nightly version'
      - run: git push
